### ISSUE TITLE
webrtc does not sync well sometimes when there are images

### ISSUE THREAD

**Issue by Marius-Romanus** [yjs/y-quill#12]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
Hello, when a second user connects to the webrtc in a quill with an image inserted, quill is not updated to what is in the webrtc, it goes blank. It doesn't always do it... although in Firefox I have gotten these two error messages, in case it can help:

![image](https://user-images.githubusercontent.com/18282247/167490645-af4786fc-1d5e-42f7-9bb6-1433d9b82d2e.png)

It only happens when the second user enters the webrtc room, if both users are already inside, it synchronizes well.
I'm in an angular environment and using ngx-quill though I don't think that has anything to do with it.

I don't know very well if it has to do with the base 64 size of the image or something like that... I have detected that when it fails and doesn't update the content it tries to make several subscriptions.

![Captura de pantalla 2022-05-11 202358](https://user-images.githubusercontent.com/18282247/167920311-5f3319f0-dba5-4193-a7cd-4634a08ec47e.png)
...
![Captura de pantalla 2022-05-11 202446](https://user-images.githubusercontent.com/18282247/167920357-3a09f329-08ca-40a9-8bc3-f31dd7da6e96.png)

On the other hand, I have also seen that when you put a password on the webrtc, it sends a first empty subscription attempt and then with the correct room. I don't know if this has to be like this since I'm new to webrtc.

And finally a third thing I've seen, although I don't think it's related to quill, it seems to do a provider.disconnect(); you are not throwing the websocket (in webrtc) from unsubscribe to the server.

I'm sorry if I don't explain myself very well in English, ask me anything you need, I'll be happy to help, you do a great job.

**To Reproduce**
1. Create an example quill with webrtc.
2. Create the webrtc server, (I have used the example you have https://github.com/yjs/y-webrtc/blob/master/bin/server.js)
3. That a user connect to the webrtc and insert an image.
4. Connect with a second user.
5. I don't know if you'll be able to reproduce it... it seems like something very specific and I haven't really found what's going on... I only know what happens when there are images...

**Expected behavior**
1. The synchronization should be correct for the second user
2. Shouldn't I throw an empty subscription websocket when the webrtc has a password? (not sure about this)
3. disconnect() should launch an unsubscribe websocket to remove it from topics

**Environment Information**
 - Chrome 101.0.4951.64 (Build oficial) (64 bits)
 - Firefox 100.0 (64-bit)
 - Node: v16.14.0
 - ws: 8.6.0
 - y-protocols: 1.0.5
 - y-quill: 0.1.5
 - y-webrtc: 10.2.3
 - yjs: 13.5.36

greetings and thanks

**Comment by dmonad** [comment]
Hi @Marius-Romanus,

I believe this issue occurs because some WebRTC implementations have a limit on the maximum message-size. So if you send something like images via WebRTC, then the message might not arrive fully on the other side. This is why you get a `out-of-bounds` error.

The following PR attempts to fix that. https://github.com/yjs/y-webrtc/pull/25

Maybe you can switch to their implementation and try out if it fixes the issue.

**Comment by Marius-Romanus** [comment]
Hello, @dmonad I have been able to verify that with the branch: https://github.com/yjs/y-webrtc/tree/fd6f29b6e692a23c7fe5034cc4eee55af98ea55c, which you indicate, it works and no longer gives that error, but on occasion it has been left in a loop launching a warning that did not contain the type of error it was giving.

![image](https://user-images.githubusercontent.com/18282247/168377890-e7714cb1-c9de-40a4-bf52-59ef1d106e2f.png)

![image](https://user-images.githubusercontent.com/18282247/168378218-2bf3e1da-07f9-405a-8e47-f0659897b97e.png)


However, I don't know if it would be correct to use it in a production environment since it is not kept up to date, a pity that the polyfill was not implemented at the moment. With your experience, do you think it is better at the moment to use websockets for large sizes instead of webrtc? Thank you very much, I hope that at least my test will serve for you to continue on that path :)

The other two errors, I imagine, are totally independent of this. (First empty subscription when webrtc has a password and disconnect doesn't send unsubcribe)

Greetings!

**Comment by dmonad** [comment]
Yeah, it might be better to revert to y-websocket for a serious application. Unfortunately, there are still compatibility issues between browsers when using webrtc-data channels.

**Comment by dmonad** [comment]
Regarding the signaling issue. I think one of my signaling servers is down at the moment. This might be the reason.
