### ISSUE TITLE
Jumping cursor

### ISSUE THREAD

**Issue by volser** [yjs/y-quill#13]
If type text at the end of the line and there is a next line, the remote cursor is jumping to the next line.

how it looks:
https://www.loom.com/share/c4a6206629dc49c6bc45bef548e2f9c3

**Comment by dmonad** [comment]
I'm not sure if we can fix that - seems to be an issue with the quill-cursors package. 

Closing, but let me know if you have an idea on how to fix this.

**Comment by volser** [comment]
@dmonad it calls move cursor 3 times on type 1 symbol.
So how issue could be in quill-cursors lib?

![image](https://user-images.githubusercontent.com/10529385/171035660-3f8c4d9f-ebda-4cff-a0e3-6b07d26dca7d.png)

**Comment by volser** [comment]
@dmonad do you know Quill's `editor-change` emits 2 different events (text-change and selection-change).
So if you type symbol it emits 2 events and first is `selection-change` and only then `text-change`.
Can it be root of the issue?
