### ISSUE TITLE
Multi formatting bug

### ISSUE THREAD

**Issue by team-c35p** [yjs/y-quill#6]
**Describe the bug**
 multi selected format changed not synced 

**To Reproduce**
1. open 2 browser(A, B) and go to  'https://demos.yjs.dev/quill/quill.html' 
2. In A, add some text multi line like
```
a
b
c
d
e

```   
3. In A, multi select from 2 to 4 lines and change type normal to H1
4. In A, multi selected lines format changed normal to H1
5. In B, only first line changed normal to H1, other lines were not chaged

**Screenshots**
![bug](https://user-images.githubusercontent.com/54426116/90608227-47943880-e23d-11ea-9064-66ffd5507344.gif)

**Environment Information**
 - use yjs, y-quill, y-websocket latest version

**Comment by manstie** [comment]
I also noticed this; any multi-line formatting (bold, ital, underline, ...) only propagates the formatting change to other clients for the first line in the selection.

**Comment by dmonad** [comment]
Fixed in yjs@13.4.11 / yjs#272
